### ISSUE TITLE
about Vision-aided UAV Navigation and Dynamic Obstacle Avoidance using Gradient-based B-spline Trajectory Optimization

### ISSUE THREAD

**Issue by jingjingdeshouhou** [Zhefan-Xu/CERLAB-UAV-Autonomy#15]
1. Regarding the calculation of the cost of static obstacles, the UAV cannot see behind the obstacles during flight, so how is the first control point of the obstacles obtained?
2. The process of executing the trajectory is to plan a straight line, while Figure 3 in the paper is a curve. Is the curve drawn to more clearly show the process of how to escape from the obstacle
Figure 4 on the calculation of the cost of dynamic obstacles I do not particularly understand whether it is necessary to draw a circle for each future position and then form a conical collision area

**Comment by Zhefan-Xu** [comment]
Hi @jingjingdeshouhou, Thanks for your questions.

1. The first control point is always the robot start position. Assuming you are talking about the first control in the trajectory that has collision avoidance behavior. The point is the result of the optimization formulation and it is not manually selected one. The UAV does not able to see things behind the obstacles but it keeps performing replanning on the fly, so as soon as it approaches and see the rear side of the obstacle, it can generate trajectories to avoid collisions.

2. Could you please elaborate the first portion? For the second portion, using ellipsoid for the future steps are to prevent collision in the future. Also, since the future prediction is not totally reliable, we reduce the size of the circle area.

Please let me know if you have further questions.
